[2024-11-03T16:24:18.051+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-03T16:24:18.060+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.transfer_task_meta manual__2024-11-03T16:24:06.302685+00:00 [queued]>
[2024-11-03T16:24:18.063+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.transfer_task_meta manual__2024-11-03T16:24:06.302685+00:00 [queued]>
[2024-11-03T16:24:18.064+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-03T16:24:18.070+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transfer_task_meta> on 2024-11-03 16:24:06.302685+00:00
[2024-11-03T16:24:18.074+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=236) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-03T16:24:18.074+0000] {standard_task_runner.py:72} INFO - Started process 241 to run task
[2024-11-03T16:24:18.075+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'transfer_task_meta', 'manual__2024-11-03T16:24:06.302685+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpmgyv5x8q']
[2024-11-03T16:24:18.076+0000] {standard_task_runner.py:105} INFO - Job 103: Subtask transfer_task_meta
[2024-11-03T16:24:18.106+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.transfer_task_meta manual__2024-11-03T16:24:06.302685+00:00 [running]> on host 2b8c286c59ee
[2024-11-03T16:24:18.140+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='transfer_task_meta' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T16:24:06.302685+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-03T16:24:06.302685+00:00'
[2024-11-03T16:24:18.142+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-03T16:24:18.151+0000] {logging_mixin.py:190} INFO - Error during import: /bin/sh: 2: gcloud: Permission denied
[2024-11-03T16:24:18.151+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-03T16:24:18.155+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-03T16:24:18.158+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=transfer_task_meta, run_id=manual__2024-11-03T16:24:06.302685+00:00, execution_date=20241103T162406, start_date=20241103T162418, end_date=20241103T162418
[2024-11-03T16:24:18.173+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-03T16:24:18.177+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
