[2024-11-03T16:11:34.799+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-03T16:11:34.806+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.transfer_task_review manual__2024-11-03T16:11:10.707485+00:00 [queued]>
[2024-11-03T16:11:34.809+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.transfer_task_review manual__2024-11-03T16:11:10.707485+00:00 [queued]>
[2024-11-03T16:11:34.810+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-03T16:11:34.814+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transfer_task_review> on 2024-11-03 16:11:10.707485+00:00
[2024-11-03T16:11:34.817+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=110) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-03T16:11:34.817+0000] {standard_task_runner.py:72} INFO - Started process 114 to run task
[2024-11-03T16:11:34.818+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'transfer_task_review', 'manual__2024-11-03T16:11:10.707485+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmprv0nfjzb']
[2024-11-03T16:11:34.819+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask transfer_task_review
[2024-11-03T16:11:34.837+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.transfer_task_review manual__2024-11-03T16:11:10.707485+00:00 [running]> on host 6458415e9821
[2024-11-03T16:11:34.863+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='transfer_task_review' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T16:11:10.707485+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-03T16:11:10.707485+00:00'
[2024-11-03T16:11:34.864+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-03T16:11:34.872+0000] {logging_mixin.py:190} INFO - Error during import: /bin/sh: 2: gcloud: Permission denied
[2024-11-03T16:11:34.872+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-03T16:11:34.875+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-03T16:11:34.876+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=transfer_task_review, run_id=manual__2024-11-03T16:11:10.707485+00:00, execution_date=20241103T161110, start_date=20241103T161134, end_date=20241103T161134
[2024-11-03T16:11:34.917+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-03T16:11:34.925+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-03T16:11:34.925+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
