[2024-11-01T19:19:13.774+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-01T19:19:13.781+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.json_to_csv_meta_data manual__2024-11-01T19:19:12.517493+00:00 [queued]>
[2024-11-01T19:19:13.784+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.json_to_csv_meta_data manual__2024-11-01T19:19:12.517493+00:00 [queued]>
[2024-11-01T19:19:13.784+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-01T19:19:13.790+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): json_to_csv_meta_data> on 2024-11-01 19:19:12.517493+00:00
[2024-11-01T19:19:13.793+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=62) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-01T19:19:13.795+0000] {standard_task_runner.py:72} INFO - Started process 74 to run task
[2024-11-01T19:19:13.795+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'json_to_csv_meta_data', 'manual__2024-11-01T19:19:12.517493+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpw349hy7s']
[2024-11-01T19:19:13.796+0000] {standard_task_runner.py:105} INFO - Job 189: Subtask json_to_csv_meta_data
[2024-11-01T19:19:13.818+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.json_to_csv_meta_data manual__2024-11-01T19:19:12.517493+00:00 [running]> on host 6bca134bba56
[2024-11-01T19:19:13.871+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='json_to_csv_meta_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-01T19:19:12.517493+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-01T19:19:12.517493+00:00'
[2024-11-01T19:19:13.874+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-01T19:19:13.948+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/src/json_to_csv.py", line 14, in json_to_csv
    download_blob(source_blob_name, temp_json_file_path)
  File "/opt/airflow/dags/src/bucket_connection.py", line 23, in download_blob
    blob.download_to_filename(destination_file_name)
  File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/blob.py", line 1345, in download_to_filename
    self._handle_filename_and_download(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/blob.py", line 1219, in _handle_filename_and_download
    with open(filename, "wb") as file_obj:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Data/temp/test_metadata.json'
[2024-11-01T19:19:13.958+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline, task_id=json_to_csv_meta_data, run_id=manual__2024-11-01T19:19:12.517493+00:00, execution_date=20241101T191912, start_date=20241101T191913, end_date=20241101T191913
[2024-11-01T19:19:13.964+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-01T19:19:13.964+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 189 for task json_to_csv_meta_data ([Errno 2] No such file or directory: 'Data/temp/test_metadata.json'; 74)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/src/json_to_csv.py", line 14, in json_to_csv
    download_blob(source_blob_name, temp_json_file_path)
  File "/opt/airflow/dags/src/bucket_connection.py", line 23, in download_blob
    blob.download_to_filename(destination_file_name)
  File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/blob.py", line 1345, in download_to_filename
    self._handle_filename_and_download(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/blob.py", line 1219, in _handle_filename_and_download
    with open(filename, "wb") as file_obj:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Data/temp/test_metadata.json'
[2024-11-01T19:19:13.976+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-01T19:19:13.985+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-01T19:19:13.987+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
