[2024-11-03T16:48:55.877+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-03T16:48:55.886+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.get_review_data manual__2024-11-03T16:48:39.491265+00:00 [queued]>
[2024-11-03T16:48:55.890+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.get_review_data manual__2024-11-03T16:48:39.491265+00:00 [queued]>
[2024-11-03T16:48:55.891+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-11-03T16:48:55.897+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_review_data> on 2024-11-03 16:48:39.491265+00:00
[2024-11-03T16:48:55.900+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=117) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-03T16:48:55.900+0000] {standard_task_runner.py:72} INFO - Started process 119 to run task
[2024-11-03T16:48:55.901+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'get_review_data', 'manual__2024-11-03T16:48:39.491265+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpr3xtubd2']
[2024-11-03T16:48:55.902+0000] {standard_task_runner.py:105} INFO - Job 185: Subtask get_review_data
[2024-11-03T16:48:55.919+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.get_review_data manual__2024-11-03T16:48:39.491265+00:00 [running]> on host f0aff20aeccb
[2024-11-03T16:48:55.945+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='get_review_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T16:48:39.491265+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-03T16:48:39.491265+00:00'
[2024-11-03T16:48:55.946+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-03T16:49:01.279+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-03T16:49:01.290+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-03T16:49:01.290+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=get_review_data, run_id=manual__2024-11-03T16:48:39.491265+00:00, execution_date=20241103T164839, start_date=20241103T164855, end_date=20241103T164901
[2024-11-03T16:49:01.318+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-03T16:49:01.330+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-03T16:49:01.331+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
