[2024-10-30T20:23:57.595+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T20:23:57.604+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.json_to_csv_meta_data manual__2024-10-30T20:05:46.293361+00:00 [queued]>
[2024-10-30T20:23:57.609+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.json_to_csv_meta_data manual__2024-10-30T20:05:46.293361+00:00 [queued]>
[2024-10-30T20:23:57.610+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-30T20:23:57.617+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): json_to_csv_meta_data> on 2024-10-30 20:05:46.293361+00:00
[2024-10-30T20:23:57.621+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=104) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-30T20:23:57.622+0000] {standard_task_runner.py:72} INFO - Started process 114 to run task
[2024-10-30T20:23:57.623+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'json_to_csv_meta_data', 'manual__2024-10-30T20:05:46.293361+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpl2l7ppmi']
[2024-10-30T20:23:57.625+0000] {standard_task_runner.py:105} INFO - Job 118: Subtask json_to_csv_meta_data
[2024-10-30T20:23:57.649+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.json_to_csv_meta_data manual__2024-10-30T20:05:46.293361+00:00 [running]> on host 6bca134bba56
[2024-10-30T20:23:57.688+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='json_to_csv_meta_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T20:05:46.293361+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T20:05:46.293361+00:00'
[2024-10-30T20:23:57.689+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-30T20:24:07.724+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-10-30T20:24:07.725+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-30T20:24:07.725+0000] {process_utils.py:132} INFO - Sending 15 to group 114. PIDs of all processes in the group: [114]
[2024-10-30T20:24:07.725+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 114
[2024-10-30T20:24:07.726+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-10-30T20:24:07.744+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-30T20:24:07.756+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=114, status='terminated', exitcode=0, started='20:23:56') (114) terminated with exit code 0
[2024-11-01T18:29:09.986+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-01T18:29:10.000+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: data_pipeline.json_to_csv_meta_data manual__2024-10-30T20:05:46.293361+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-11-01T18:29:10.013+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
